// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iacpnvyybfxgoyckxpia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhY3Budnl5YmZ4Z295Y2t4cGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzQ1MTksImV4cCI6MjA3MTU1MDUxOX0.Azc1dIqHs807BkBqslwyaIm-cVam9Pn1-zPvaQiI3Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});